### PR TITLE
Initial commit for the QuickstartNewProject2DWithExtendedFlexibleUI.

### PR DESCRIPTION
**Pull request by Fogsight**

### CODE REVIEW

**Comment by harryshipton** [comment]
Hi @Fogsight, could you choose a license for your project and add it to your project? You can get more information for that in `CONTRIBUTING.md`.

**Comment by Fogsight** [comment]
Updated license.

**Comment by harryshipton** [comment]
Just waiting on someone from @Game-Dev-Network/unity2d-approvers to approve this and then I'll approve and merge it.

**Comment by Fogsight** [comment]
I think it's at its final version now. Ready to be reviewed. :)

**Review by domingo-osorio — DISMISSED** [review]
👍

**Review by svens-uk — CHANGES_REQUESTED** [review]
Is there any chance of reducing the size of the `Assets` folder? For example, TextMesh Pro contains the `Documentation` folder—is that needed? Currently the snippet stands at 0.5% maximum repo limit before we start getting unhappy emails from GitHub, so if possible I'd like to reduce this as much as possible.

Is there perhaps a way to remove the assets folder but let people know how to add the assets folder? If not then that's fine, we can try minimising it in other ways.

**Review by svens-uk — DISMISSED** [review]

**Review by domingo-osorio — DISMISSED** [review]
:+1:

**Comment by Fogsight** [comment]
I've created a separate repository for my project with the same license file so I can update it more often (In the description). I'll create pull requests here on major changes only.

**Review by domingo-osorio — DISMISSED** [review]
:+1:

**Pull request merged**
